### ISSUE TITLE
Plugin crashes on loading on Android Studio

### ISSUE THREAD

**Issue by TheFreezingChicken** [kagof/intellij-pokemon-progress#35]
**Description of the bug & expected behaviour**

When launching, Android Studio reports a crash of the plugin with this [stacktrace](https://github.com/kagof/intellij-pokemon-progress/files/5710274/stacktrace.txt)

**Environment Info**

* **OS:** Windows 10 Build 19041
* **JetBrains Product:** Android Studio
* **JetBrains Product Version:** 4.1.1
* **Plugin Version:** 1.3.0

**Steps to reproduce**

Just installing the plugin.

**Additional context or information**

I spotted this line in the stacktrace
`com/kagof/intellij/plugins/pokeprogress/PokemonProgressListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: com.kagof.pokeprogress]`

Maybe Android Studio uses a bundled version of the JRE which is old? Just a guess though.
Anyway, I also tried other "Nyan progress bar" based plugins (the original included) and they all work fine.

**Comment by kagof** [comment]
Thanks for the bug report @TheFreezingChicken. The latest version of this plugin was indeed compiled with Java 11 (which corresponds to 55.0) instead of Java 8 (which corresponds to 52).

The release notes for the latest version of IntelliJ seemed to suggest that all IntelliJ based IDEs had been updated to run on Java 11, but that apparently doesn't apply to Android Studio. Also weirdly, version 1.3.0 of this plugin does run on older versions of IntelliJ (back to 2019.3) which _are_ Java 8 based. It seems Android Studio may be the odd one out.

I am able to repro the error you posted, so will look into resolving this. It may (hopefully) just be as easy as reverting back to using Java 8 instead of 11 to compile this plugin.

**Comment by kagof** [comment]
Bizarrely, the compatibility checker says that it _is_ compatible, and that it used Java 11 to check it!

<img width="1237" alt="Screenshot 2020-12-19 at 17 34 25" src="https://user-images.githubusercontent.com/17553493/102695657-9d471480-4220-11eb-9377-2ea4bddd55f0.png">

**Comment by TheFreezingChicken** [comment]
I'm not even surprised, everything that Google touches is a structural mess (that somehow still works but still... a mess).
So considering Android Studio is probably 95% under Google's directions that's why I'm not surprised.
I even felt bad putting it under "JetBrains Product" because it feels like an insult 😂

**Comment by kagof** [comment]
Merry Christmas @TheFreezingChicken! I've released version 1.3.1 of the plugin. All I did was rollback the Java version to 8, which seems to have made it work in Android studio. Should be available in the plugin repository some time in the next day or 2.

**Comment by TheFreezingChicken** [comment]
Merry Christmas to you too 😄 and thanks. I've being trying the plugin on WebStorm too in the meanwhile, really cool 👍🏻
