### ISSUE TITLE
Allow fixed progress bar size

### ISSUE THREAD

**Issue by liyiwei979621500** [kagof/intellij-pokemon-progress#74]
**Current behaviour (optional)**

Progress bar now changes size to match the sprite's size

**Description of the desired feature (required)**

Allow fixed size

**Comment by kagof** [comment]
Hi @liyiwei979621500, 

I recently changed this behaviour with the 2.0.0 release, in order to keep the sprites looking nice instead of becoming blurry as they're scaled down. 

That being said, I can understand why this would be desired to keep them at a fixed size.

I can see how I would go about doing this. The sprites might look a bit different than they used to as I'll be scaling them at runtime, but it should be possible to add this as a feature in a 2.1.0 release. 

In the mean time, if you want to avoid the larger progress bars, you can disable the Pokémon with larger sprites (which I do realize is a bit of a pain).

**Comment by B0BAI** [comment]
I uninstall because of this too. The size disparity is unattractive and distracting, too, when working.

_Please update us when you have fixed it._ 

Also, why not use SVG if you are concerned about the images being blurry?

**Comment by kagof** [comment]
Hi @B0BAI, I understand why you don't like the change. I should be able to work on this over the weekend, so hopefully it'll be available early next week.

> Also, why not use SVG if you are concerned about blurry images?

I've looked into this quite a bit, and done an extensive amount of testing with it. There's two main issues.

1. the rendering of SVGs seems to just look worse than the GIFs even when they're unscaled. I'm not really certain why this is, since IntelliJ does use SVGs for a lot of their own icons.
2. at the end of the day, these are 32x32 pixel art images (or in some cases 64x64) that are trying to be displayed in a 20px high progress bar. Some of the sprites don't take up the full 32px of height, and so they display just fine. But some of them do. If you take a pixel art image that is 32x32 and try to make it smaller than that, you're going to lose information. This is regardless of the format, SVG doesn't help here. Imagine trying to squeeze an SVG into a 1x1px space; it's impossible to do that without losing something in the process, and it's a similar concept here.

I do still actually want to transition this project to using SVGs over GIFs (assuming I figure out the first point) as I think I could do some cool things with them and it would likely reduce the package size of this plugin, but it isn't a silver bullet for this issue unfortunately.

**Comment by B0BAI** [comment]
Thanks @kagof for responding and also considering a fix. Either gif or SVG, I still think you have a fantastic plugin, and I can't wait for the update next week.

**Comment by B0BAI** [comment]
Thanks for the flexibility you put in place. Love it.

**Comment by liyiwei979621500** [comment]
Thanks
